CREATE TABLE [dbo].[listings] (
    [listing_id] INT NOT NULL,
    [name] NVARCHAR(255),
    [host_id] INT,
    [host_since] DATE,
    [host_location] NVARCHAR(255),
    [host_response_time] NVARCHAR(50),
    [host_response_rate] INT,
    [host_acceptance_rate] INT,
    [host_is_superhost] NVARCHAR(1),
    [host_total_listings_count] INT,
    [host_has_profile_pic] NVARCHAR(1),
    [host_identity_verified] NVARCHAR(1),
    [neighbourhood] NVARCHAR(255),
    [district] NVARCHAR(255),
    [city] NVARCHAR(255),
    [latitude] FLOAT,
    [longitude] FLOAT,
    [property_type] NVARCHAR(50),
    [room_type] NVARCHAR(50),
    [accommodates] INT,
    [bedrooms] INT,
    [amenities] NVARCHAR(MAX), -- Pode ser ajustado dependendo do tamanho máximo das amenidades
    [price] FLOAT,
    [minimum_nights] INT,
    [maximum_nights] INT,
    [review_scores_rating] INT,
    [review_scores_accuracy] INT,
    [review_scores_cleanliness] INT,
    [review_scores_checkin] INT,
    [review_scores_communication] INT,
    [review_scores_location] INT,
    [review_scores_value] INT,
    [instant_bookable] NVARCHAR(1)
);
